### PR TITLE
Feat rplibs rpsbml

### PR DESCRIPTION
**Pull request by guillaume-gricourt**
Add some methods to rplibs, rpSBML class : 
- search_compartment_id() rename to has_compartment()
- add has_specie()
- add has_reaction()

### CODE REVIEW

**Comment by breakthewall** [comment]
I'm ok but I would like some changes:
- `has_compartment()` should only return a boolean. I would write a method `get_compartment()` which would return a string and could call `has_compartment()` if needed;
- `has_specie()`: same
- `has_reaction()`: same

**Comment by breakthewall** [comment]
ok, this is much better now.
One question: why do you to import `rpCompound` and `rpReaction` in `rpSBML`?

**Comment by guillaume-gricourt** [comment]
They are used into `has_specie()` and `has_reaction()` arguments. You could send to the functions a `str`, an `rpObject` or a `libsbml.Object`.
Maybe this conversion will be done by the user and let only `str` object in arguments of the functions ?

**Comment by breakthewall** [comment]
In this case, just remove rpObject but you can let str or libsbml object.

**Comment by guillaume-gricourt** [comment]
Ok, I removed `rpObject` and `libsbml.Object` in arguments of the `search_specie()` `search_reaction()` functions to keep an homogeneity with `search_compartment()`
Do you agree ?

**Comment by guillaume-gricourt** [comment]
Please, don't merge now, I need to check some stuff

**Pull request merged**
